public void testOtherException() {
    IOException exception = new IOException("test exception");
    InputStream closed = new ClosedInputStream();
    TaggedInputStream stream = new TaggedInputStream(closed);
    assertFalse(stream.isCauseOf(exception));
    assertFalse(stream.isCauseOf(new TaggedIOException(exception, closed)));
    try {
        stream.throwIfCauseOf(exception);
    } catch (IOException e) {
        fail("Unexpected exception thrown");
    }
    try {
        stream.throwIfCauseOf(new TaggedIOException(exception, closed));
    } catch (IOException e) {
        fail("Unexpected exception thrown");
    }
}