@Test
public void testOtherException() throws Exception {
    final IOException exception = new IOException("test exception");
    final InputStream closed = new ClosedInputStream();
    final TaggedInputStream stream = new TaggedInputStream(closed);
    assertFalse(stream.isCauseOf(exception));
    assertFalse(stream.isCauseOf(new TaggedIOException(exception, UUID.randomUUID())));
    try {
        stream.throwIfCauseOf(exception);
    } catch (final IOException e) {
        fail("Unexpected exception thrown");
    }
    try {
        stream.throwIfCauseOf(new TaggedIOException(exception, UUID.randomUUID()));
    } catch (final IOException e) {
        fail("Unexpected exception thrown");
    }
    stream.close();
}